-- ============================================================================
-- SCRIPT DE MIGRATION POSTGRESQL → ORACLE (VERSION 2 - FINALE)
-- ============================================================================
-- Base source      : AURA (PostgreSQL)
-- Base cible       : Oracle Database 12c+
-- Date génération  : 2025-11-07 04:11:38
-- Version          : 2 - CONTRAINTES CHECK CORRIGÉES
-- ============================================================================
--
-- CORRECTIONS VERSION 2:
--   ✅ Contraintes CHECK utilisent les vrais noms de colonnes
--   ✅ account.role (pas accountroleenum)
--   ✅ account.typeOfAccount (pas accounttypeofaccountenum)
--   ✅ company.companyValidated (pas companycompanyvalidatedenum)
--   ✅ companymembership.status (pas companymembershipstatusenum)
--   ✅ order.status (pas orderstatusenum)
--   ✅ subscription.subscriptionStatus (pas subscriptionsubscriptionstatusenum)
--
-- EXÉCUTION:
--   SQL*Plus: @schemas_oracle.sql
--
-- ============================================================================

SET ECHO ON;
SET FEEDBACK ON;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR CONTINUE;


-- ============================================================================
-- MIGRATION POSTGRESQL → ORACLE (VERSION 3 - PRESERVE CASE)
-- ============================================================================
-- Tous les identifiants sont encadrés de guillemets doubles pour préserver
-- la casse exacte des noms d'objets source.
-- ============================================================================

-- CRÉATION DES TABLES

CREATE TABLE "account" (
 "accountId" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "email" VARCHAR2(4000) NOT NULL,
 "password" VARCHAR2(4000) NOT NULL,
 "firstName" VARCHAR2(4000) NOT NULL,
 "lastName" VARCHAR2(4000) NOT NULL,
 "phoneNumber" VARCHAR2(4000) NOT NULL,
 "role" VARCHAR2(11) DEFAULT 'ADMIN' NOT NULL,
 "typeOfAccount" VARCHAR2(8) DEFAULT 'PERSONAL' NOT NULL,
 "isEnabled" NUMBER(1) DEFAULT 0 NOT NULL,
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "authorizedDevice" CLOB DEFAULT '[]' NOT NULL,
 "addressId" NUMBER(10),
 "passwordResetToken" VARCHAR2(4000),
 "providerRegister" VARCHAR2(4000)
);

CREATE TABLE "address" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "street" VARCHAR2(4000),
 "region" VARCHAR2(4000),
 "postalCode" VARCHAR2(4000),
 "country" VARCHAR2(4000),
 "countryOfDomicile" VARCHAR2(4000),
 "city" VARCHAR2(4000)
);

CREATE TABLE "alias_easytransac_transaction" (
 "id" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "ClientId" VARCHAR2(4000),
 "ClientIP" VARCHAR2(4000),
 "Alias" VARCHAR2(4000),
 "CardMonth" VARCHAR2(4000),
 "CardYear" VARCHAR2(4000),
 "CardCVV" VARCHAR2(4000),
 "CardNumber" VARCHAR2(4000),
 "CardOwner" VARCHAR2(4000),
 "LastName" VARCHAR2(4000),
 "FirstName" VARCHAR2(4000),
 "Email" VARCHAR2(4000),
 "PhoneNumber" VARCHAR2(4000),
 "ZipCode" VARCHAR2(4000),
 "City" VARCHAR2(4000),
 "Street" VARCHAR2(4000)
);

CREATE TABLE "chargeback" (
 "chargebackId" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "tId" VARCHAR2(4000) NOT NULL,
 "amount" NUMBER(10) NOT NULL,
 "status" CLOB,
 "processedAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "reason" CLOB,
 "description" CLOB
);

CREATE TABLE "checkout" (
 "checkoutId" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "modifiedAtributes" CLOB DEFAULT '[]' NOT NULL,
 "logo" VARCHAR2(4000),
 "billingMode" VARCHAR2(4000),
 "title" VARCHAR2(4000) NOT NULL,
 "slug" VARCHAR2(4000) NOT NULL,
 "isPublished" NUMBER(1) DEFAULT 0 NOT NULL,
 "templateId" NUMBER(10) NOT NULL,
 "createdAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "updatedAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "amount" NUMBER,
 "recurrence" VARCHAR2(4000),
 "paymentMethod" CLOB DEFAULT '[]' NOT NULL,
 "paymentNumber" CLOB DEFAULT '[]' NOT NULL,
 "createByAccountId" VARCHAR2(36),
 "commercialName" VARCHAR2(4000),
 "isDeleted" NUMBER(1) DEFAULT 0 NOT NULL,
 "hooksUrlHookId" VARCHAR2(36)
);

CREATE TABLE "checkout_product" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "quantity" NUMBER(10) NOT NULL,
 "productId" NUMBER(10),
 "checkoutCheckoutId" VARCHAR2(36)
);

CREATE TABLE "checkout_session" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "sessionId" VARCHAR2(4000) NOT NULL,
 "userId" VARCHAR2(4000),
 "status" VARCHAR2(4000) NOT NULL,
 "createdAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "updatedAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "orderId" NUMBER(10)
);

CREATE TABLE "company" (
 "companyId" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "companyName" VARCHAR2(4000) NOT NULL,
 "companyPhoneNumber" VARCHAR2(4000) NOT NULL,
 "companyReference" VARCHAR2(4000) NOT NULL,
 "managerName" VARCHAR2(4000) NOT NULL,
 "activitySociety" VARCHAR2(4000),
 "activitySociety_other" VARCHAR2(4000),
 "companyStatus" VARCHAR2(4000) NOT NULL,
 "companyValidated" VARCHAR2(9) DEFAULT 'PENDING' NOT NULL,
 "companyHistory" CLOB DEFAULT '[]',
 "addressId" NUMBER(10),
 "createByAccountId" VARCHAR2(36),
 "commercialName" VARCHAR2(4000)
);

CREATE TABLE "company_membership" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "status" VARCHAR2(9) DEFAULT 'PENDING' NOT NULL,
 "memberHistory" CLOB DEFAULT '[]',
 "joinedAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
 "accountAccountId" VARCHAR2(36),
 "companyCompanyId" VARCHAR2(36),
 "approvedByAccountId" VARCHAR2(36)
);

CREATE TABLE "hooks_url" (
 "hookId" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "webhookUrl" VARCHAR2(4000) NOT NULL,
 "crmName" VARCHAR2(4000) NOT NULL,
 "createBy" VARCHAR2(36) NOT NULL
);

CREATE TABLE "industry" (
 "industryId" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "name" VARCHAR2(4000) NOT NULL
);

CREATE TABLE "job_run_history" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "jobName" VARCHAR2(4000) NOT NULL,
 "startedAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "finishedAt" TIMESTAMP,
 "status" VARCHAR2(4000) DEFAULT 'SUCCESS' NOT NULL,
 "errorMessage" CLOB
);

CREATE TABLE "kyc" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "identityProof" VARCHAR2(4000),
 "bankDetails" VARCHAR2(4000),
 "registrationCertificate" VARCHAR2(4000),
 "companyStatus" VARCHAR2(4000),
 "beneficialOwnersRegister" VARCHAR2(4000),
 "accountHolder" VARCHAR2(4000),
 "iban" VARCHAR2(4000),
 "bic" VARCHAR2(4000),
 "beneficialOwners" VARCHAR2(4000),
 "beneficialName" VARCHAR2(4000),
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "companyCompanyId" VARCHAR2(36),
 "averageMonthlyRevenueFile" VARCHAR2(4000),
 "refundRateFile" VARCHAR2(4000),
 "chargebackRateFile" VARCHAR2(4000),
 "averageMonthlyRevenue" NUMBER,
 "refundRate" NUMBER,
 "chargebackRate" NUMBER,
 "salesTax" VARCHAR2(4000)
);

CREATE TABLE "merchant" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "merchantId" VARCHAR2(4000),
 "accountAccountId" VARCHAR2(36),
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE "merchant_payout" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "merchantId" VARCHAR2(4000) NOT NULL,
 "amount" NUMBER(12,2) NOT NULL,
 "fee" NUMBER(12,2) DEFAULT '0' NOT NULL,
 "status" VARCHAR2(20) NOT NULL,
 "createdAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "paidAt" TIMESTAMP,
 "details" CLOB
);

CREATE TABLE "notifications" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "message" VARCHAR2(4000) NOT NULL,
 "is_read" NUMBER(1) DEFAULT 0 NOT NULL,
 "data" CLOB,
 "created_at" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "account_id" VARCHAR2(36),
 "entity" VARCHAR2(4000),
 "typeAction" VARCHAR2(4000)
);

CREATE TABLE "order" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "totalAmount" NUMBER NOT NULL,
 "paymentMethod" VARCHAR2(4000) NOT NULL,
 "idTransaction" VARCHAR2(4000),
 "status" VARCHAR2(9) DEFAULT 'PENDING' NOT NULL,
 "customerId" NUMBER(10),
 "checkoutCheckoutId" VARCHAR2(36),
 "selectedPaymentNumber" VARCHAR2(4000),
 "commissionAmount" NUMBER,
 "commissionRate" NUMBER,
 "pricingCommissionId" NUMBER(10),
 "parentOrderId" NUMBER(10),
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE "order_customer" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "firstname" VARCHAR2(4000),
 "lastname" VARCHAR2(4000),
 "email" VARCHAR2(4000),
 "phone" VARCHAR2(4000),
 "addressId" NUMBER(10),
 "professional" VARCHAR2(4000) DEFAULT 'PARTICULAR',
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "vatNumber" VARCHAR2(4000)
);

CREATE TABLE "pricing_commission" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "paymentMethod" VARCHAR2(4000) NOT NULL,
 "country" VARCHAR2(4000) NOT NULL,
 "merchantCountry" VARCHAR2(4000) NOT NULL,
 "rate" NUMBER(5,2) NOT NULL,
 "aditionalRate" NUMBER(5,2) DEFAULT '0' NOT NULL,
 "createdAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "updatedAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "accountsAccountId" VARCHAR2(36)
);

CREATE TABLE "product" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "name" VARCHAR2(4000) NOT NULL,
 "description" VARCHAR2(4000),
 "productType" VARCHAR2(4000),
 "formation" VARCHAR2(4000),
 "formationType" VARCHAR2(4000),
 "createByAccountId" VARCHAR2(36),
 "urlVente" VARCHAR2(4000),
 "urlReturn" VARCHAR2(4000),
 "modeEco" VARCHAR2(4000),
 "duration" VARCHAR2(4000),
 "durationNumber" NUMBER(10),
 "durationType" VARCHAR2(4000),
 "taciteReconduction" NUMBER(1),
 "basePrice" NUMBER DEFAULT '0' NOT NULL,
 "status" VARCHAR2(4000) DEFAULT 'PENDING',
 "installments" CLOB DEFAULT '1',
 "paymentMethod" CLOB,
 "isProfessionalTraining" NUMBER(1) DEFAULT 0 NOT NULL,
 "contentLink" VARCHAR2(4000),
 "descriptionPdfPath" VARCHAR2(4000),
 "durationHours" BINARY_FLOAT,
 "participantLogs" CLOB,
 "quizLink" VARCHAR2(4000),
 "specificTermsFilePath" VARCHAR2(4000),
 "specialtyCodeCode" VARCHAR2(5)
);

CREATE TABLE "product_variant" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "sku" VARCHAR2(4000) NOT NULL,
 "metadata" CLOB DEFAULT '[]',
 "stock" NUMBER(10) DEFAULT 0 NOT NULL,
 "priceAdjustment" NUMBER(10) DEFAULT 0 NOT NULL,
 "productId" NUMBER(10)
);

CREATE TABLE "refresh_token" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "token" VARCHAR2(4000) NOT NULL,
 "userAgent" VARCHAR2(4000) NOT NULL,
 "ipAddress" VARCHAR2(4000),
 "createdAt" TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
 "expiresAt" TIMESTAMP,
 "userAccountId" VARCHAR2(36)
);

CREATE TABLE "refund" (
 "refundId" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "tId" VARCHAR2(4000) NOT NULL,
 "amount" NUMBER(10) NOT NULL,
 "status" CLOB,
 "requestedAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "processedAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
 "reason" CLOB
);

CREATE TABLE "session" (
 "sessionId" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "token" VARCHAR2(150) NOT NULL,
 "sub" VARCHAR2(4000) NOT NULL,
 "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE "stock" (
 "id" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "quantity" NUMBER(10) NOT NULL,
 "productId" NUMBER(10),
 "isDeleted" NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE "subscription" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "subscribeAt" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
 "subscriptionExpiration" TIMESTAMP WITH TIME ZONE NOT NULL,
 "subscriptionMonth" NUMBER(10) NOT NULL,
 "tid" VARCHAR2(4000),
 "accountAccountId" VARCHAR2(36),
 "totalAmount" NUMBER DEFAULT '0' NOT NULL,
 "subscriptionStatus" VARCHAR2(9) DEFAULT 'PENDING' NOT NULL,
 "orderId" VARCHAR2(4000),
 "subscriptionType" VARCHAR2(4000) DEFAULT 'SALE'
);

CREATE TABLE "template" (
 "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 "allAtributes" CLOB DEFAULT '[]' NOT NULL,
 "logo" VARCHAR2(4000),
 "billingMode" VARCHAR2(4000) NOT NULL,
 "paymentMethod" VARCHAR2(4000) NOT NULL,
 "paymentNumber" NUMBER(10) NOT NULL,
 "title" VARCHAR2(4000) NOT NULL,
 "templateLink" VARCHAR2(4000) NOT NULL
);

CREATE TABLE "training_specialty" (
 "code" VARCHAR2(5) NOT NULL,
 "label" VARCHAR2(100) NOT NULL,
 "category" VARCHAR2(50) NOT NULL
);

CREATE TABLE "transaction" (
 "id" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "amount" NUMBER(10,2) NOT NULL,
 "date" TIMESTAMP NOT NULL,
 "transactionId" VARCHAR2(4000) NOT NULL,
 "status" VARCHAR2(4000) NOT NULL,
 "orderId" NUMBER(10)
);

CREATE TABLE "transaction_product" (
 "id" VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
 "quantity" NUMBER(10) NOT NULL,
 "productId" NUMBER(10),
 "transactionId" VARCHAR2(36),
 "price" NUMBER
);

-- CONTRAINTES

ALTER TABLE "account" ADD CONSTRAINT "PK_b1a9fdd281787a66a213f5b725b" PRIMARY KEY ("accountId");
ALTER TABLE "account" ADD CONSTRAINT "REL_d96017d82b031439613c39c1ec" UNIQUE ("addressId");
ALTER TABLE "account" ADD CONSTRAINT "UQ_4c8f96ccf523e9a3faefd5bdd4c" UNIQUE ("email");
ALTER TABLE "account" ADD CONSTRAINT "FK_d96017d82b031439613c39c1ecb" FOREIGN KEY ("addressId") REFERENCES "address"("id");

ALTER TABLE "address" ADD CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id");

ALTER TABLE "alias_easytransac_transaction" ADD CONSTRAINT "PK_446a99aa28482ba5ed2323163ca" PRIMARY KEY ("id");

ALTER TABLE "chargeback" ADD CONSTRAINT "PK_8ee00965129c22914d9895aa340" PRIMARY KEY ("chargebackId");

ALTER TABLE "checkout" ADD CONSTRAINT "PK_e300b1d5c7adcd9d0c7499c8ea7" PRIMARY KEY ("checkoutId");
ALTER TABLE "checkout" ADD CONSTRAINT "FK_51e52ce2e88fd4c282ad86e68f0" FOREIGN KEY ("createByAccountId") REFERENCES "account"("accountId");
ALTER TABLE "checkout" ADD CONSTRAINT "FK_a168e0c74e8b67d39c9aba78fa6" FOREIGN KEY ("hooksUrlHookId") REFERENCES "hooks_url"("hookId");
ALTER TABLE "checkout" ADD CONSTRAINT "FK_a274a6bbd8048d88393c17cf19f" FOREIGN KEY ("templateId") REFERENCES "template"("id");

ALTER TABLE "checkout_product" ADD CONSTRAINT "PK_c02b08a73c5dfc53a4ac125bdc1" PRIMARY KEY ("id");
ALTER TABLE "checkout_product" ADD CONSTRAINT "FK_3553482d3f1b2a63b17a2ae707d" FOREIGN KEY ("checkoutCheckoutId") REFERENCES "checkout"("checkoutId");
ALTER TABLE "checkout_product" ADD CONSTRAINT "FK_9dbd67446bb2ee198f0c43687d9" FOREIGN KEY ("productId") REFERENCES "product"("id");

ALTER TABLE "checkout_session" ADD CONSTRAINT "PK_143bac9b20b973e700fc05ee4e7" PRIMARY KEY ("id");
ALTER TABLE "checkout_session" ADD CONSTRAINT "REL_756d86dbc4f717876228d17247" UNIQUE ("orderId");
ALTER TABLE "checkout_session" ADD CONSTRAINT "FK_756d86dbc4f717876228d172474" FOREIGN KEY ("orderId") REFERENCES "order"("id");

ALTER TABLE "company" ADD CONSTRAINT "PK_81611e86d930483997273420166" PRIMARY KEY ("companyId");
ALTER TABLE "company" ADD CONSTRAINT "REL_3737905699894299444476dd79" UNIQUE ("addressId");
ALTER TABLE "company" ADD CONSTRAINT "REL_47cf9d44a6e7fc3d8070b31274" UNIQUE ("createByAccountId");
ALTER TABLE "company" ADD CONSTRAINT "FK_3737905699894299444476dd79c" FOREIGN KEY ("addressId") REFERENCES "address"("id");
ALTER TABLE "company" ADD CONSTRAINT "FK_47cf9d44a6e7fc3d8070b31274b" FOREIGN KEY ("createByAccountId") REFERENCES "account"("accountId");

ALTER TABLE "company_membership" ADD CONSTRAINT "PK_ae6501e8c46bf49e6bc1fdf4736" PRIMARY KEY ("id");
ALTER TABLE "company_membership" ADD CONSTRAINT "FK_82da554596a8bd920e7d9f02812" FOREIGN KEY ("approvedByAccountId") REFERENCES "account"("accountId");
ALTER TABLE "company_membership" ADD CONSTRAINT "FK_d0ac4fe8d944962bce07817054a" FOREIGN KEY ("companyCompanyId") REFERENCES "company"("companyId");
ALTER TABLE "company_membership" ADD CONSTRAINT "FK_e63658dc436e2165176e5ca5732" FOREIGN KEY ("accountAccountId") REFERENCES "account"("accountId");

ALTER TABLE "hooks_url" ADD CONSTRAINT "PK_8137c3ddaf3bbce310192a3349f" PRIMARY KEY ("hookId");
ALTER TABLE "hooks_url" ADD CONSTRAINT "FK_0545b3efdb3fc0a64791b4108ea" FOREIGN KEY ("createBy") REFERENCES "account"("accountId");

ALTER TABLE "industry" ADD CONSTRAINT "PK_ea8f8164276d8ca0bd6f2b68256" PRIMARY KEY ("industryId");

ALTER TABLE "job_run_history" ADD CONSTRAINT "PK_93aa05ffdc71e9fec020570b8cb" PRIMARY KEY ("id");

ALTER TABLE "kyc" ADD CONSTRAINT "PK_84ab2e81ea9700d29dda719f3be" PRIMARY KEY ("id");
ALTER TABLE "kyc" ADD CONSTRAINT "REL_aa5b246812c2da451ed37aa5b5" UNIQUE ("companyCompanyId");
ALTER TABLE "kyc" ADD CONSTRAINT "FK_aa5b246812c2da451ed37aa5b52" FOREIGN KEY ("companyCompanyId") REFERENCES "company"("companyId");

ALTER TABLE "merchant" ADD CONSTRAINT "PK_9a3850e0537d869734fc9bff5d6" PRIMARY KEY ("id");
ALTER TABLE "merchant" ADD CONSTRAINT "REL_759ca3a7c38fa9a9993ae75ced" UNIQUE ("accountAccountId");
ALTER TABLE "merchant" ADD CONSTRAINT "FK_759ca3a7c38fa9a9993ae75ced3" FOREIGN KEY ("accountAccountId") REFERENCES "account"("accountId");

ALTER TABLE "merchant_payout" ADD CONSTRAINT "PK_f653061ed6249cb590330d47417" PRIMARY KEY ("id");

ALTER TABLE "notifications" ADD CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id");
ALTER TABLE "notifications" ADD CONSTRAINT "FK_a1ec3b4b4f2017665b534e60256" FOREIGN KEY ("account_id") REFERENCES "account"("accountId");

ALTER TABLE "order" ADD CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id");
ALTER TABLE "order" ADD CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "order_customer"("id");
ALTER TABLE "order" ADD CONSTRAINT "FK_1e19d7ec382e32650bd256e6b9b" FOREIGN KEY ("checkoutCheckoutId") REFERENCES "checkout"("checkoutId");
ALTER TABLE "order" ADD CONSTRAINT "FK_6cad3cc900079dd19cb6e23b3d0" FOREIGN KEY ("parentOrderId") REFERENCES "order"("id");
ALTER TABLE "order" ADD CONSTRAINT "FK_6fd17a0a1fe4ef854278aabc549" FOREIGN KEY ("pricingCommissionId") REFERENCES "pricing_commission"("id");

ALTER TABLE "order_customer" ADD CONSTRAINT "PK_cd7812c96209c5bdd48a6b858b0" PRIMARY KEY ("id");
ALTER TABLE "order_customer" ADD CONSTRAINT "REL_58b7fdd3204c9777e8426486a9" UNIQUE ("addressId");
ALTER TABLE "order_customer" ADD CONSTRAINT "FK_58b7fdd3204c9777e8426486a96" FOREIGN KEY ("addressId") REFERENCES "address"("id");

ALTER TABLE "pricing_commission" ADD CONSTRAINT "PK_fb4a57ac6c854f2ce09a2e72629" PRIMARY KEY ("id");
ALTER TABLE "pricing_commission" ADD CONSTRAINT "FK_50d5890907c4189e80337d98036" FOREIGN KEY ("accountsAccountId") REFERENCES "account"("accountId");

ALTER TABLE "product" ADD CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id");
ALTER TABLE "product" ADD CONSTRAINT "FK_2daed336de9a754b94b194decc6" FOREIGN KEY ("specialtyCodeCode") REFERENCES "training_specialty"("code");
ALTER TABLE "product" ADD CONSTRAINT "FK_d16578d138e45af98dd4cc4822e" FOREIGN KEY ("createByAccountId") REFERENCES "account"("accountId");

ALTER TABLE "product_variant" ADD CONSTRAINT "PK_1ab69c9935c61f7c70791ae0a9f" PRIMARY KEY ("id");
ALTER TABLE "product_variant" ADD CONSTRAINT "FK_6e420052844edf3a5506d863ce6" FOREIGN KEY ("productId") REFERENCES "product"("id");

ALTER TABLE "refresh_token" ADD CONSTRAINT "PK_b575dd3c21fb0831013c909e7fe" PRIMARY KEY ("id");
ALTER TABLE "refresh_token" ADD CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token");
ALTER TABLE "refresh_token" ADD CONSTRAINT "FK_329f89d2c99a5a0ab6d47503e02" FOREIGN KEY ("userAccountId") REFERENCES "account"("accountId");

ALTER TABLE "refund" ADD CONSTRAINT "PK_14cd319e17940a28952b929f2de" PRIMARY KEY ("refundId");

ALTER TABLE "session" ADD CONSTRAINT "PK_6f8fc3d2111ccc30d98e173d8dd" PRIMARY KEY ("sessionId");

ALTER TABLE "stock" ADD CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id");
ALTER TABLE "stock" ADD CONSTRAINT "REL_e855a71c31948188c2bf78824a" UNIQUE ("productId");
ALTER TABLE "stock" ADD CONSTRAINT "FK_e855a71c31948188c2bf78824a5" FOREIGN KEY ("productId") REFERENCES "product"("id");

ALTER TABLE "subscription" ADD CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id");
ALTER TABLE "subscription" ADD CONSTRAINT "FK_b65c9b85625b6506c82f555d0c6" FOREIGN KEY ("accountAccountId") REFERENCES "account"("accountId");

ALTER TABLE "template" ADD CONSTRAINT "PK_fbae2ac36bd9b5e1e793b957b7f" PRIMARY KEY ("id");

ALTER TABLE "training_specialty" ADD CONSTRAINT "PK_5c805ae5eb7882a7a20710000ce" PRIMARY KEY ("code");

ALTER TABLE "transaction" ADD CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id");
ALTER TABLE "transaction" ADD CONSTRAINT "FK_a6e45c89cfbe8d92840266fd30f" FOREIGN KEY ("orderId") REFERENCES "order"("id");

ALTER TABLE "transaction_product" ADD CONSTRAINT "PK_1801daeaeaaaef2aeb63ae80a67" PRIMARY KEY ("id");
ALTER TABLE "transaction_product" ADD CONSTRAINT "UQ_8c7bab603ba2932263fff704be3" UNIQUE ("transactionId", "productId");
ALTER TABLE "transaction_product" ADD CONSTRAINT "FK_3dc6e0b30199d17c2e027dcbdee" FOREIGN KEY ("productId") REFERENCES "product"("id");
ALTER TABLE "transaction_product" ADD CONSTRAINT "FK_60ae1f8b2678568d30d9bbadb26" FOREIGN KEY ("transactionId") REFERENCES "transaction"("id");

-- CONTRAINTES CHECK POUR LES TYPES ENUM

ALTER TABLE "account" ADD CONSTRAINT chk_account_role CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'USER', 'MERCHANT'));

ALTER TABLE "account" ADD CONSTRAINT chk_account_typeOfAccount CHECK (typeOfAccount IN ('BUSINESS', 'PERSONAL'));

ALTER TABLE "company" ADD CONSTRAINT chk_company_companyValidated CHECK (companyValidated IN ('PENDING', 'APPROUVED', 'REJECTED', 'STAGING'));

ALTER TABLE "company_membership" ADD CONSTRAINT chk_company_membership_status CHECK (status IN ('PENDING', 'APPROUVED', 'REJECTED', 'STAGING'));

ALTER TABLE "order" ADD CONSTRAINT chk_order_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'PARTIAL', 'REFUNDED'));

ALTER TABLE "subscription" ADD CONSTRAINT chk_subscription_subscriptionS CHECK (subscriptionStatus IN ('ACTIVE', 'INACTIVE', 'PENDING', 'CANCELLED', 'EXPIRED', 'SUSPENDED'));

-- INDEX


-- ============================================================================
-- FIN DE LA MIGRATION
-- ============================================================================


-- ============================================================================
-- FIN DU SCRIPT DE MIGRATION
-- ============================================================================

COMMIT;

-- Vérifications:
-- SELECT COUNT(*) FROM user_tables;                    -- 30 tables
-- SELECT COUNT(*) FROM user_constraints WHERE constraint_type = 'C';  -- Contraintes CHECK
-- SELECT constraint_name, search_condition FROM user_constraints WHERE table_name = 'ACCOUNT' AND constraint_type = 'C';
